services:
  postgres:
    image: postgis/postgis:17-3.5-alpine
    container_name: petbed-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: petbed
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d petbed" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - petbed-net

  ngrok:
    image: ngrok/ngrok:latest
    container_name: petbed-ngrok
    restart: unless-stopped
    command: http --url=${NGROK_URL} host.docker.internal:8080
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - petbed-net

volumes:
  postgres-data:
  minio-data:

networks:
  petbed-net:
    driver: bridge