spring:
  application:
    name: pet-bed
  config:
    import: optional:classpath:local.properties

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/petbed}
    username: ${SPRING_DATASOURCE_USERNAME:petbed}
    password: ${SPRING_DATASOURCE_PASSWORD:petbed_secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
    enabled: true


aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT}
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_S3_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}


telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    webhook-url: ${TELEGRAM_BOT_WEBHOOK_URL}
    path: webhook

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: info
    org.telegram: DEBUG